server {
    listen 80;
    server_name rese.eto-tech.com;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://rese-front-nginx-1:80;
    }
}

server {
    listen 80;
    server_name runmaru.eto-tech.com;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://laravel-run-maru-app-nginx-1:80;
    }
}