resolver 127.0.0.11 ipv6=off valid=30s;
resolver_timeout 5s;

server {
    listen 80;
    server_name rese.eto-tech.com runmaru.eto-tech.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name rese.eto-tech.com;

    ssl_certificate     /etc/letsencrypt/live/rese.eto-tech.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rese.eto-tech.com/privkey.pem;

    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;
    ssl_session_tickets off;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        set $upstream_rese http://rese-web:80;
        proxy_pass $upstream_rese;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name runmaru.eto-tech.com;

    ssl_certificate     /etc/letsencrypt/live/rese.eto-tech.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rese.eto-tech.com/privkey.pem;

    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;
    ssl_session_tickets off;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        set $upstream_runmaru http://runmaru-web:80;
        proxy_pass $upstream_runmaru;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
    }
}